"""Definitions and runtime registry for UL's built-in augmentations.

See ``README.md`` beside this file for the complete operator index.
"""

from ul_core.augmentations.authoring import (
    AugmentationDefinition,
    AugmentationLibrary,
    AugmentationRuntimeBinding,
    AugmentationRuntimeKind,
    AugmentationValidatorRuntime,
    ConversationModifierBinding,
    ConversationModifierRuntime,
    DeterministicTransformBinding,
    DeterministicTransformRuntime,
    EnvironmentScheduleBinding,
    EnvironmentScheduleRuntime,
    FaultControlBinding,
    FaultControlRuntime,
    InstalledRuntimeBinding,
    RegisteredAugmentation,
    RegisteredRuntimeBinding,
    SemanticRendererBinding,
    SemanticRendererRuntime,
    ValidatorBinding,
    builtin_augmentation_library,
)
from ul_core.augmentations.bundles import (
    AugmentationBundle,
    AugmentationBundleBudget,
    AugmentationBundleCatalog,
    AugmentationBundlePlan,
    BundleBindingReadiness,
    BundleOperatorPolicy,
    BundlePlanTotals,
    BundleProbePlan,
    BundleSourceCase,
    builtin_augmentation_bundle_catalog,
    plan_augmentation_bundle,
)
from ul_core.augmentations.definitions import (
    AugmentationBinding,
    AugmentationRef,
    AugmentationRequirements,
    BuiltinAugmentationCatalog,
    BuiltinAugmentationSpec,
    builtin_augmentation_catalog,
)
from ul_core.augmentations.projections import (
    AugmentationChangeSet,
    AugmentationProjection,
    AugmentationTargetSurface,
    ProjectionContract,
    ProjectionTarget,
    ProjectionTargetOperation,
)
from ul_core.augmentations.registry import (
    AugmentationRegistry,
    ValidationResult,
    builtin_augmentation_registry,
)

__all__ = [
    "AugmentationBinding",
    "AugmentationBundle",
    "AugmentationBundleBudget",
    "AugmentationBundleCatalog",
    "AugmentationBundlePlan",
    "AugmentationChangeSet",
    "AugmentationDefinition",
    "AugmentationLibrary",
    "AugmentationProjection",
    "AugmentationRef",
    "AugmentationRegistry",
    "AugmentationRequirements",
    "AugmentationRuntimeBinding",
    "AugmentationRuntimeKind",
    "AugmentationTargetSurface",
    "AugmentationValidatorRuntime",
    "BuiltinAugmentationCatalog",
    "BuiltinAugmentationSpec",
    "BundleBindingReadiness",
    "BundleOperatorPolicy",
    "BundlePlanTotals",
    "BundleProbePlan",
    "BundleSourceCase",
    "ConversationModifierBinding",
    "ConversationModifierRuntime",
    "DeterministicTransformBinding",
    "DeterministicTransformRuntime",
    "EnvironmentScheduleBinding",
    "EnvironmentScheduleRuntime",
    "FaultControlBinding",
    "FaultControlRuntime",
    "InstalledRuntimeBinding",
    "ProjectionContract",
    "ProjectionTarget",
    "ProjectionTargetOperation",
    "RegisteredAugmentation",
    "RegisteredRuntimeBinding",
    "SemanticRendererBinding",
    "SemanticRendererRuntime",
    "ValidationResult",
    "ValidatorBinding",
    "builtin_augmentation_bundle_catalog",
    "builtin_augmentation_catalog",
    "builtin_augmentation_library",
    "builtin_augmentation_registry",
    "plan_augmentation_bundle",
]
