"""Public Python SDK for UL."""

from ul_core.augmentation import builtin_augmentation_registry
from ul_core.contracts import DatasetTargetExecutor, SemanticEquivalenceVerifier
from ul_core.coverage import CoverageArchive
from ul_core.dataset import (
    InteractionRecord,
    ObservedAgentOutput,
    RenderedUserInput,
    SemanticDelta,
    SemanticEquivalenceAssessment,
    SemanticFrame,
    UserInputRecord,
)
from ul_core.models import (
    Action,
    ActionEffect,
    CampaignResult,
    ExecutionMode,
    ExecutionResult,
    ExecutionStatus,
    FindingSeverity,
    MaterializedScenario,
    OracleFinding,
    SafetyEnvelope,
    Scenario,
    ScenarioProvenance,
)
from ul_core.prompts import PromptManager, PromptTemplateInfo

from ul.campaign import CampaignRunner
from ul.dataset_augmentation import (
    DatasetAugmentationEngine,
    DatasetAugmentationOperator,
    DatasetAugmentationResult,
    builtin_dataset_augmentation_operators,
)
from ul.dataset_evaluation import (
    DatasetEvaluationBaseline,
    DatasetEvaluationCase,
    DatasetEvaluationFinding,
    DatasetEvaluationOutcomeGroup,
    DatasetEvaluationResult,
    DatasetEvaluationRunner,
    DatasetEvaluationTrial,
    DatasetEvaluationTrialSet,
)
from ul.dataset_invariants import (
    DatasetInvariantArmEvaluation,
    DatasetInvariantArrayUniqueRuleEvaluation,
    DatasetInvariantArrayUniqueTrialEvaluation,
    DatasetInvariantEvaluation,
    DatasetInvariantRuleEvaluation,
    DatasetInvariantSuite,
    DatasetInvariantTrialEvaluation,
    DatasetInvariantValueEqualsRuleEvaluation,
    DatasetInvariantValueEqualsTrialEvaluation,
    DatasetInvariantValueInSetRuleEvaluation,
    DatasetInvariantValueInSetTrialEvaluation,
    JsonArrayItemsUniqueByInvariant,
    JsonValueEqualsLiteralInvariant,
    JsonValueInAllowedSetInvariant,
    JsonValuesEqualInvariant,
    evaluate_dataset_invariant_rules,
    evaluate_dataset_invariants,
    load_dataset_invariant_suite,
)
from ul.dataset_regression import (
    DatasetRegressionCase,
    DatasetRegressionExecution,
    DatasetRegressionInvariantSuite,
    DatasetRegressionLineage,
    DatasetRegressionResult,
    DatasetRegressionRunCaseResult,
    DatasetRegressionRunResult,
    DatasetRegressionTargetSnapshot,
    DatasetRegressionVariation,
    create_dataset_regression_case,
    dataset_regression_target_config_sha256,
    load_dataset_regression_case,
    replay_dataset_regression,
    run_dataset_regressions,
)
from ul.deconstruction import (
    DatasetSemanticProviderSelection,
    OpenAICompatibleDatasetSettings,
    OpenAICompatibleSemanticDeconstructor,
    OpenRouterDatasetSettings,
    OpenRouterSemanticDeconstructor,
    SemanticCompletionProvider,
    SemanticModelDeconstructor,
    create_semantic_model_deconstructor,
    load_dataset_semantic_settings,
)
from ul.http_target import (
    JsonHttpDatasetTarget,
    JsonHttpDatasetTargetConfig,
    load_json_http_dataset_target_config,
)
from ul.otlp_ingest import OtlpIngestResult, OtlpInteractionRecord, parse_otlp_traces

__all__ = [
    "Action",
    "ActionEffect",
    "CampaignResult",
    "CampaignRunner",
    "CoverageArchive",
    "DatasetAugmentationEngine",
    "DatasetAugmentationOperator",
    "DatasetAugmentationResult",
    "DatasetEvaluationBaseline",
    "DatasetEvaluationCase",
    "DatasetEvaluationFinding",
    "DatasetEvaluationOutcomeGroup",
    "DatasetEvaluationResult",
    "DatasetEvaluationRunner",
    "DatasetEvaluationTrial",
    "DatasetEvaluationTrialSet",
    "DatasetInvariantArmEvaluation",
    "DatasetInvariantArrayUniqueRuleEvaluation",
    "DatasetInvariantArrayUniqueTrialEvaluation",
    "DatasetInvariantEvaluation",
    "DatasetInvariantRuleEvaluation",
    "DatasetInvariantSuite",
    "DatasetInvariantTrialEvaluation",
    "DatasetInvariantValueEqualsRuleEvaluation",
    "DatasetInvariantValueEqualsTrialEvaluation",
    "DatasetInvariantValueInSetRuleEvaluation",
    "DatasetInvariantValueInSetTrialEvaluation",
    "DatasetRegressionCase",
    "DatasetRegressionExecution",
    "DatasetRegressionInvariantSuite",
    "DatasetRegressionLineage",
    "DatasetRegressionResult",
    "DatasetRegressionRunCaseResult",
    "DatasetRegressionRunResult",
    "DatasetRegressionTargetSnapshot",
    "DatasetRegressionVariation",
    "DatasetSemanticProviderSelection",
    "DatasetTargetExecutor",
    "ExecutionMode",
    "ExecutionResult",
    "ExecutionStatus",
    "FindingSeverity",
    "InteractionRecord",
    "JsonArrayItemsUniqueByInvariant",
    "JsonHttpDatasetTarget",
    "JsonHttpDatasetTargetConfig",
    "JsonValueEqualsLiteralInvariant",
    "JsonValueInAllowedSetInvariant",
    "JsonValuesEqualInvariant",
    "MaterializedScenario",
    "ObservedAgentOutput",
    "OpenAICompatibleDatasetSettings",
    "OpenAICompatibleSemanticDeconstructor",
    "OpenRouterDatasetSettings",
    "OpenRouterSemanticDeconstructor",
    "OracleFinding",
    "OtlpIngestResult",
    "OtlpInteractionRecord",
    "PromptManager",
    "PromptTemplateInfo",
    "RenderedUserInput",
    "SafetyEnvelope",
    "Scenario",
    "ScenarioProvenance",
    "SemanticCompletionProvider",
    "SemanticDelta",
    "SemanticEquivalenceAssessment",
    "SemanticEquivalenceVerifier",
    "SemanticFrame",
    "SemanticModelDeconstructor",
    "UserInputRecord",
    "builtin_augmentation_registry",
    "builtin_dataset_augmentation_operators",
    "create_dataset_regression_case",
    "create_semantic_model_deconstructor",
    "dataset_regression_target_config_sha256",
    "evaluate_dataset_invariant_rules",
    "evaluate_dataset_invariants",
    "load_dataset_invariant_suite",
    "load_dataset_regression_case",
    "load_dataset_semantic_settings",
    "load_json_http_dataset_target_config",
    "parse_otlp_traces",
    "replay_dataset_regression",
    "run_dataset_regressions",
]
