"""Core primitives for UL."""

from ul_core.augmentation import (
    AugmentationRegistry,
    builtin_augmentation_registry,
)
from ul_core.augmentation_catalog import (
    AugmentationBinding,
    AugmentationExecutionOwner,
    AugmentationRef,
    AugmentationRequirements,
    BuiltinAugmentationCatalog,
    BuiltinAugmentationSpec,
    builtin_augmentation_catalog,
)
from ul_core.contracts import ProductionSource, SemanticEquivalenceVerifier
from ul_core.coverage import (
    CoverageArchive,
    DeterministicAugmentationSelector,
    extract_semantic_coverage,
)
from ul_core.dataset import (
    ObservedAgentOutput,
    SemanticDelta,
    SemanticEquivalenceAssessment,
)
from ul_core.evaluation import (
    EnvironmentCapabilities,
    EnvironmentLifecycleEvidence,
    EnvironmentResetEvidence,
    EnvironmentStateEvidence,
    EnvironmentTurnEvidence,
    EvaluationCase,
    ExecutionEvidence,
    ProductionObservation,
    ProductionSourcePage,
    StateObservationAuthority,
    TimeoutAfterCommitEventEvidence,
    TimeoutAfterCommitEventRequest,
    TimeoutAfterCommitTriggerStatus,
)
from ul_core.evaluators import (
    CallableEvaluator,
    EvaluationResults,
    EvaluationSubject,
    EvaluatorDecision,
    EvaluatorEvidence,
    EvaluatorResult,
    EvaluatorSpec,
    ExactValueEvaluator,
    HttpEvaluationResult,
    HttpResultEvaluator,
    HumanReviewEvaluator,
    JsonPropertyEvaluator,
    PairwiseEvaluator,
    RubricEvaluator,
    StateChangeEvaluator,
    ToolCallEvaluator,
)
from ul_core.models import (
    AugmentationApplication,
    CampaignCaseResult,
    CampaignResult,
    ExecutionResult,
    ExecutionStatus,
    FindingSeverity,
    OracleFinding,
    OracleRelation,
    Scenario,
)
from ul_core.prompts import PromptManager, PromptTemplateInfo

__all__ = [
    "AugmentationApplication",
    "AugmentationBinding",
    "AugmentationExecutionOwner",
    "AugmentationRef",
    "AugmentationRegistry",
    "AugmentationRequirements",
    "BuiltinAugmentationCatalog",
    "BuiltinAugmentationSpec",
    "CallableEvaluator",
    "CampaignCaseResult",
    "CampaignResult",
    "CoverageArchive",
    "DeterministicAugmentationSelector",
    "EnvironmentCapabilities",
    "EnvironmentLifecycleEvidence",
    "EnvironmentResetEvidence",
    "EnvironmentStateEvidence",
    "EnvironmentTurnEvidence",
    "EvaluationCase",
    "EvaluationResults",
    "EvaluationSubject",
    "EvaluatorDecision",
    "EvaluatorEvidence",
    "EvaluatorResult",
    "EvaluatorSpec",
    "ExactValueEvaluator",
    "ExecutionEvidence",
    "ExecutionResult",
    "ExecutionStatus",
    "FindingSeverity",
    "HttpEvaluationResult",
    "HttpResultEvaluator",
    "HumanReviewEvaluator",
    "JsonPropertyEvaluator",
    "ObservedAgentOutput",
    "OracleFinding",
    "OracleRelation",
    "PairwiseEvaluator",
    "ProductionObservation",
    "ProductionSource",
    "ProductionSourcePage",
    "PromptManager",
    "PromptTemplateInfo",
    "RubricEvaluator",
    "Scenario",
    "SemanticDelta",
    "SemanticEquivalenceAssessment",
    "SemanticEquivalenceVerifier",
    "StateChangeEvaluator",
    "StateObservationAuthority",
    "TimeoutAfterCommitEventEvidence",
    "TimeoutAfterCommitEventRequest",
    "TimeoutAfterCommitTriggerStatus",
    "ToolCallEvaluator",
    "builtin_augmentation_catalog",
    "builtin_augmentation_registry",
    "extract_semantic_coverage",
]
